# Generated by Django 5.2.6 on 2025-09-30 23:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pos_x', models.PositiveIntegerField(default=0)),
                ('pos_y', models.PositiveIntegerField(default=0)),
                ('direction', models.CharField(choices=[('NORTH', 'North'), ('EAST', 'East'), ('SOUTH', 'South'), ('WEST', 'West')], default='NORTH', max_length=5)),
                ('mesh_x', models.PositiveIntegerField(default=5)),
                ('mesh_y', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
